### ISSUE TITLE
rucksack-css

### ISSUE THREAD

**Issue by kfuchs** [seaneking/gulp-rucksack#4]
rucksack-css@1.0.2 is breaking.

**Comment by seaneking** [comment]
Stacktrace?

**Comment by kfuchs** [comment]
Sorry I was being lazy earlier ;).

```
events.js:160
      throw er; // Unhandled 'error' event
      ^
TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
    at fromObject (buffer.js:262:9)
    at Function.Buffer.from (buffer.js:101:10)
    at new Buffer (buffer.js:80:17)
    at Transform.stream._transform (project/node_modules/gulp-rucksack/index.js:38:27)
    at Transform._read (_stream_transform.js:167:10)
    at Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:331:12)
    at writeOrBuffer (_stream_writable.js:317:5)
    at Transform.Writable.write (_stream_writable.js:243:11)
    at write (project/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:623:24)
```

I tracked it down to dependency differences. One setup works, because I npm installed a while ago, but when I setup the project again it has that issue. 


Here is the new NON-WORKING dep tree:
```
├─┬ gulp-rucksack@0.1.3
│ ├── object-assign@4.1.1
│ ├─┬ rucksack-css@1.0.2
│ │ ├─┬ autoprefixer@7.1.2
│ │ │ ├─┬ browserslist@2.3.3
│ │ │ │ └── electron-to-chromium@1.3.18
│ │ │ ├── caniuse-lite@1.0.30000715
│ │ │ ├── normalize-range@0.1.2
│ │ │ ├── num2fraction@1.2.2
│ │ │ └── postcss-value-parser@3.3.0
│ │ ├─┬ laggard@2.0.1
│ │ │ ├─┬ pixrem@4.0.1
│ │ │ │ └─┬ reduce-css-calc@1.3.0
│ │ │ │   ├── balanced-match@0.4.2
│ │ │ │   ├── math-expression-evaluator@1.2.17
│ │ │ │   └─┬ reduce-function-call@1.0.2
│ │ │ │     └── balanced-match@0.4.2
│ │ │ └── postcss-will-change@2.0.0
│ │ ├─┬ postcss@6.0.9
│ │ │ ├─┬ chalk@2.1.0
│ │ │ │ └─┬ ansi-styles@3.2.0
│ │ │ │   └─┬ color-convert@1.9.0
│ │ │ │     └── color-name@1.1.3
│ │ │ └─┬ supports-color@4.2.1
│ │ │   └── has-flag@2.0.0
│ │ ├── postcss-alias@2.0.0
│ │ ├── postcss-clearfix@2.0.1
│ │ ├─┬ postcss-color-rgba-fallback@3.0.0
│ │ │ └── rgb-hex@2.1.0
│ │ ├── postcss-easings@1.0.0
│ │ ├── postcss-fontpath@1.0.0
│ │ ├── postcss-hexrgba@1.0.0
│ │ ├── postcss-input-style@1.0.0
│ │ ├── postcss-opacity@5.0.0
│ │ ├── postcss-position@1.0.0
│ │ ├── postcss-pseudoelements@5.0.0
│ │ ├─┬ postcss-quantity-queries@0.5.0
│ │ │ └── balanced-match@0.4.2
│ │ ├─┬ postcss-reporter@5.0.0
│ │ │ ├─┬ chalk@2.1.0
│ │ │ │ ├── ansi-styles@3.2.0
│ │ │ │ └── supports-color@4.2.1
│ │ │ ├── lodash@4.17.4
│ │ │ └─┬ log-symbols@2.0.0
│ │ │   └─┬ chalk@2.1.0
│ │ │     ├── ansi-styles@3.2.0
│ │ │     └── supports-color@4.2.1
│ │ ├── postcss-responsive-type@1.0.0
│ │ ├── postcss-vmin@3.0.0
│ │ ├─┬ read-file-stdin@0.2.1
│ │ │ └── gather-stream@1.0.0
│ │ └── write-file-stdout@0.0.2
│ └─┬ vinyl-sourcemaps-apply@0.2.1
│   └── source-map@0.5.6
```


Here is the old WORKING dep tree.
```
├─┬ gulp-rucksack@0.1.3
│ ├── object-assign@4.1.1
│ ├─┬ rucksack-css@0.9.1
│ │ ├─┬ autoprefixer@6.7.7
│ │ │ ├─┬ browserslist@1.7.7
│ │ │ │ └── electron-to-chromium@1.3.2
│ │ │ ├── caniuse-db@1.0.30000649
│ │ │ ├── normalize-range@0.1.2
│ │ │ ├── num2fraction@1.2.2
│ │ │ ├─┬ postcss@5.2.16
│ │ │ │ └── supports-color@3.2.3
│ │ │ └── postcss-value-parser@3.3.0
│ │ ├─┬ laggard@0.1.0
│ │ │ ├─┬ pixrem@3.0.2
│ │ │ │ ├── browserslist@1.7.7
│ │ │ │ ├─┬ postcss@5.2.17
│ │ │ │ │ └── supports-color@3.2.3
│ │ │ │ └─┬ reduce-css-calc@1.3.0
│ │ │ │   ├── math-expression-evaluator@1.2.16
│ │ │ │   └── reduce-function-call@1.0.2
│ │ │ ├─┬ postcss@5.2.17
│ │ │ │ └── supports-color@3.2.3
│ │ │ ├── postcss-opacity@3.0.0
│ │ │ ├─┬ postcss-reporter@1.4.1
│ │ │ │ └── lodash@4.17.4
│ │ │ └─┬ postcss-will-change@1.1.0
│ │ │   └─┬ postcss@5.2.17
│ │ │     └── supports-color@3.2.3
│ │ ├─┬ postcss@5.2.17
│ │ │ ├── js-base64@2.1.9
│ │ │ └─┬ supports-color@3.2.3
│ │ │   └── has-flag@1.0.0
│ │ ├─┬ postcss-alias@1.0.0
│ │ │ └─┬ postcss@5.2.17
│ │ │   └── supports-color@3.2.3
│ │ ├─┬ postcss-clearfix@1.0.0
│ │ │ └─┬ postcss@5.2.17
│ │ │   └── supports-color@3.2.3
│ │ ├─┬ postcss-color-rgba-fallback@2.2.0
│ │ │ ├─┬ postcss@5.2.17
│ │ │ │ └── supports-color@3.2.3
│ │ │ └── rgb-hex@1.0.0
│ │ ├─┬ postcss-easings@0.3.0
│ │ │ └─┬ postcss@5.2.17
│ │ │   └── supports-color@3.2.3
│ │ ├─┬ postcss-fontpath@0.3.0
│ │ │ ├── object-assign@4.1.1
│ │ │ └─┬ postcss@5.2.17
│ │ │   └── supports-color@3.2.3
│ │ ├─┬ postcss-hexrgba@0.2.1
│ │ │ └─┬ postcss@5.2.17
│ │ │   └── supports-color@3.2.3
│ │ ├─┬ postcss-input-style@0.3.0
│ │ │ └─┬ postcss@5.2.17
│ │ │   └── supports-color@3.2.3
│ │ ├─┬ postcss-opacity@4.0.0
│ │ │ └─┬ postcss@5.2.17
│ │ │   └── supports-color@3.2.3
│ │ ├─┬ postcss-position@0.5.0
│ │ │ └─┬ postcss@5.2.17
│ │ │   └── supports-color@3.2.3
│ │ ├─┬ postcss-pseudoelements@3.0.0
│ │ │ └─┬ postcss@5.2.17
│ │ │   └── supports-color@3.2.3
│ │ ├─┬ postcss-quantity-queries@0.4.0
│ │ │ ├── balanced-match@0.2.1
│ │ │ └─┬ postcss@5.2.17
│ │ │   └── supports-color@3.2.3
│ │ ├─┬ postcss-reporter@2.0.0
│ │ │ ├── lodash@4.17.4
│ │ │ ├── log-symbols@1.0.2
│ │ │ └─┬ postcss@5.2.17
│ │ │   └── supports-color@3.2.3
│ │ ├─┬ postcss-responsive-type@0.5.1
│ │ │ └─┬ postcss@5.2.17
│ │ │   └── supports-color@3.2.3
│ │ ├─┬ postcss-vmin@2.0.0
│ │ │ └─┬ postcss@5.2.17
│ │ │   └── supports-color@3.2.3
│ │ ├─┬ read-file-stdin@0.2.1
│ │ │ └── gather-stream@1.0.0
│ │ └── write-file-stdout@0.0.2
│ └─┬ vinyl-sourcemaps-apply@0.2.1
│   └── source-map@0.5.6
```

The big difference is `rucksack-css`, in package.json changing `"rucksack-css": "latest",` to `0.9.1` would fix it.

**Comment by kfuchs** [comment]
PSS: For anyone who stumbles on this. My current work around was to use `npm shrinkwrap` and force `rucksack-css@0.9.1`

**Comment by kentmw** [comment]
@kfuchs I've never used shrinkwrap before. Do you mind showing how you shinkwrapped/forced 0.9.1? I ran `npm shrinkwrap` and can't seem to get it to work after that.

**Comment by kfuchs** [comment]
You'll likely need to run `npm shrinkwrap --dev` because you probably have `gulp-rucksack` as a devdep.

When you run it you should get a `npm-shrinkwrap.json` file. And you'll find something like this within it:

```
{
  "dependencies": {
   
          ...
   
    "rucksack-css": {
      "version": "0.9.1",
      "from": "rucksack-css@latest",
      "resolved": "https://registry.npmjs.org/rucksack-css/-/rucksack-css-0.9.1.tgz",
      "dev": true,
      "dependencies": {
        "postcss": {
          "version": "5.2.17",
          "from": "postcss@>=5.0.0 <6.0.0",
          "resolved": "https://registry.npmjs.org/postcss/-/postcss-5.2.17.tgz",
          "dev": true
        },
        "supports-color": {
          "version": "3.2.3",
          "from": "supports-color@^3.2.3",
          "resolved": "https://registry.npmjs.org/supports-color/-/supports-color-3.2.3.tgz",
          "dev": true
        }
      }
    }

        ...

  }
}
```

That's the `rucksack-css` version you want if you're facing this issue. You'll have to re-run `npm install`and it will use the shrinkwrap file to install dependencies. 

The package-lock.json file is the more modern way of doing it. shrinkwrap was the older way, and if you needed some backward compatibility.

**Comment by seaneking** [comment]
Hrmph. Not sure what in 1.0 would have borked this, other than the fact that it only supports Node 4+ now (for PostCSS 6). Will take a look. 

Thanks for reporting, and for the hack to fix in the meantime 👍

**Comment by kentmw** [comment]
This problem has been reoccurring in many of my projects, and having a shrinkwrap json file to manage is a huge pain just for this library. This is a major issue.

**Comment by seaneking** [comment]
Hey sorry I've been flat out recently and haven't had much time for OSS work. Will try to look into it this week, and obviously happy to take a PR addressing this

**Comment by seaneking** [comment]
Also, if gulp-rucksack is the issue, you can always just use gulp-postcss and use Rucksack as a postcss plugin instead.

I've actually been thinking of deprecating these build tool helpers in favour of that more standard workflow.

**Comment by seaneking** [comment]
Yep, going to follow the lead of other postcss-based frameworks like cssnext and cssnano, and deprecate these runners.

So, to use Rucksack with Gulp:

```js
const postcss = require('gulp-postcss');
const rucksack = require('rucksack-css');

gulp.task('styles', () => {
  return gulp.src('src/style.css')
    .pipe(postcss([
      rucksack()
    ])
    .pipe(gulp.dest('dist'));
});
